# version: '3.9'

services:

  django_app:
    build: .
    volumes:
      - staticfiles:/var/www/html/static
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      HOST: ${HOST}
      PORT: ${PORT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - "8000:8000"
    entrypoint: ['/usr/local/bin/start-django.sh']

  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    environment:
      SERVER_NAME: ${SERVER_NAME}
      DOMAIN: ${DOMAIN}
    ports: 
      - 80:80 # Puerto http 
      - 443:443 # Puerto https
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      # - ./start-nginx.sh:/usr/local/bin/start-nginx.sh
      - staticfiles:/var/www/html/static
      # - static:/var/www/html/static
      - ./config/certbot/certs:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: ['/bin/bash','/usr/local/bin/start-nginx.sh']
    depends_on:
      - django_app

volumes:
  certs:
  staticfiles:
  certbot-www:

