# version: '3.9'

services:

  cerbot:
    build: 
      context: .
      dockerfile: Dockerfile.certbot
    volumes:
      - ./config/certbot/certs:/etc/letsencrypt:rw # Montar el volumen para los certificados
      - certbot-www:/var/www/certbot:rw # Montar el volumen para la verfificacion de certificados
      - ./config/nginx/conf.d:/etc/nginx/conf.d # Montar la configuración de Nginx
    environment:
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL}
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    entrypoint: ['/usr/local/bin/start-certbot.sh']
    # depends_on:
    #   - django_app
    user: "${USER_UID}:${USER_GID}"

volumes:
  certs:
  certbot-www: