# Generated by Django 5.1 on 2024-08-23 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='entity',
            new_name='company',
        ),
    ]
