# Generated by Django 5.1 on 2024-08-24 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_entity_product_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='code',
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(db_column='product', default='999999999', on_delete=django.db.models.deletion.CASCADE, related_name='Price', to='products.product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='product',
            field=models.ForeignKey(db_column='product', default='999999999', on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='products.product'),
        ),
    ]
