# Generated by Django 5.1 on 2024-08-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_price_code_remove_stock_code_price_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='product',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='product',
            new_name='code',
        ),
    ]
