# Generated by Django 5.1 on 2024-08-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_price_code_rename_product_stock_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='code',
            field=models.ForeignKey(db_column='code', default='999999999', on_delete=django.db.models.deletion.CASCADE, related_name='Price', to='products.product'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.ForeignKey(db_column='code', default='999999999', on_delete=django.db.models.deletion.CASCADE, related_name='Stock', to='products.product'),
        ),
    ]
