# Generated by Django 5.1 on 2024-09-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_price_code_alter_stock_code'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['code'], name='price_code_index'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['datetime_scraper'], name='price_datetime_scraper_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['code'], name='product_code_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='product_company_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='product_brand_index'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='product_category_index'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['code'], name='stock_code_index'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['datetime_scraper'], name='stock_datetime_scraper_index'),
        ),
    ]
